# Generated by Django 3.2.3 on 2021-06-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='datetime_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
