# Generated by Django 3.2.3 on 2021-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_example_datetime_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='date_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
